numero = float(input("Digite o numero que deseja mostrar na tabuada: "))
if numero == numero:
  print(f"Numero x 1 = {numero * 1}")
  print(f"Numero x 2 = {numero * 2}")
  print(f"Numero x 3 = {numero * 3}")
  print(f"Numero x 4 = {numero * 4}")
  print(f"Numero x 5 = {numero * 5}")
  print(f"Numero x 6 = {numero * 6}")
  print(f"Numero x 7 = {numero * 7}")
  print(f"Numero x 8 = {numero * 8}")
  print(f"Numero x 9 = {numero * 9}")
  print(f"Numero x 10 = {numero * 10}")
  print(f"Numero x 11 = {numero * 11}")